// Package tlsutil provides the small certificate authority that stele
// operators use to issue client certificates to producers.
//
// What this gives us. Combined with TLS on the operator's ingest
// endpoint, every appended envelope now must arrive over a connection
// authenticated by a client cert the operator's CA signed. The cert's
// Common Name is bound to the envelope's ProducerID — so an attacker who
// stole a producer's signing key but cannot also obtain its TLS client
// cert is now stopped at the network layer, before the envelope is even
// parsed.
//
// Design choice: we use a single in-process CA generated by the operator
// during setup. This is the right trade-off for stele's threat model —
// a public CA would add no security against the actual threats (private
// keys / coercion of operators) and would be operationally absurd.
//
// Certificates are Ed25519-signed and short-lived (90 days by default).
// Producers rotate by re-running `stele ca-issue-producer`; old certs
// expire naturally.
package tlsutil

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DefaultCALifetime is how long a freshly-issued CA cert is valid for.
const DefaultCALifetime = 10 * 365 * 24 * time.Hour // 10 years

// DefaultLeafLifetime is how long server and client leaf certs are
// valid for. Short enough to force regular rotation; long enough that
// you don't need a CD pipeline to issue them.
const DefaultLeafLifetime = 90 * 24 * time.Hour // 90 days

// CA wraps a certificate authority private key + its certificate.
type CA struct {
	Cert    *x509.Certificate
	Priv    ed25519.PrivateKey
	CertPEM []byte
}

// GenerateCA generates a fresh Ed25519 root CA for `org`. The resulting
// CA can sign both server and client certificates.
func GenerateCA(org string) (*CA, error) {
	if org == "" {
		return nil, errors.New("tlsutil: CA org required")
	}
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, err
	}
	serial, err := randomSerial()
	if err != nil {
		return nil, err
	}
	now := time.Now()
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   "stele " + org + " root CA",
			Organization: []string{org},
		},
		NotBefore:             now.Add(-1 * time.Minute),
		NotAfter:              now.Add(DefaultCALifetime),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true, // CA can only sign leaves, not intermediate CAs
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, pub, priv)
	if err != nil {
		return nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, err
	}
	return &CA{
		Cert:    cert,
		Priv:    priv,
		CertPEM: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
	}, nil
}

// WriteCA writes the CA's certificate (PEM) to certPath and the private
// key (PKCS#8 PEM) to keyPath. The private key file is 0o600.
func (c *CA) WriteCA(certPath, keyPath string) error {
	if err := os.MkdirAll(filepath.Dir(certPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(certPath, c.CertPEM, 0o644); err != nil {
		return err
	}
	keyDER, err := x509.MarshalPKCS8PrivateKey(c.Priv)
	if err != nil {
		return err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})
	if err := os.MkdirAll(filepath.Dir(keyPath), 0o700); err != nil {
		return err
	}
	return os.WriteFile(keyPath, keyPEM, 0o600)
}

// LoadCA reads a CA certificate + private key from disk.
func LoadCA(certPath, keyPath string) (*CA, error) {
	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("read CA cert: %w", err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		return nil, fmt.Errorf("parse CA cert: %w", err)
	}
	keyPEM, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("read CA key: %w", err)
	}
	priv, err := parsePrivateKeyPEM(keyPEM)
	if err != nil {
		return nil, fmt.Errorf("parse CA key: %w", err)
	}
	return &CA{Cert: cert, Priv: priv, CertPEM: certPEM}, nil
}

// IssueServerCert issues a server certificate for the operator daemon.
// hosts is the list of DNS names and IP addresses the cert should be
// valid for (e.g. ["stele.example.com", "127.0.0.1", "::1"]).
func (c *CA) IssueServerCert(commonName string, hosts []string, lifetime time.Duration) (certPEM []byte, keyPEM []byte, err error) {
	if lifetime == 0 {
		lifetime = DefaultLeafLifetime
	}
	return c.issueLeaf(commonName, hosts, lifetime, x509.ExtKeyUsageServerAuth)
}

// IssueClientCert issues a client certificate for a producer. The
// Common Name MUST be the producer ID — stele's mTLS verification step
// reads CN to bind the connection to the envelope's ProducerID.
func (c *CA) IssueClientCert(producerID string, lifetime time.Duration) (certPEM []byte, keyPEM []byte, err error) {
	if producerID == "" {
		return nil, nil, errors.New("tlsutil: producer ID required")
	}
	if lifetime == 0 {
		lifetime = DefaultLeafLifetime
	}
	return c.issueLeaf(producerID, nil, lifetime, x509.ExtKeyUsageClientAuth)
}

func (c *CA) issueLeaf(commonName string, hosts []string, lifetime time.Duration, eku x509.ExtKeyUsage) ([]byte, []byte, error) {
	leafPub, leafPriv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	serial, err := randomSerial()
	if err != nil {
		return nil, nil, err
	}
	now := time.Now()
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: commonName, Organization: c.Cert.Subject.Organization},
		NotBefore:    now.Add(-1 * time.Minute),
		NotAfter:     now.Add(lifetime),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{eku},
	}
	for _, h := range hosts {
		if ip := net.ParseIP(h); ip != nil {
			tmpl.IPAddresses = append(tmpl.IPAddresses, ip)
		} else {
			tmpl.DNSNames = append(tmpl.DNSNames, h)
		}
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, c.Cert, leafPub, c.Priv)
	if err != nil {
		return nil, nil, err
	}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyDER, err := x509.MarshalPKCS8PrivateKey(leafPriv)
	if err != nil {
		return nil, nil, err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})
	return certPEM, keyPEM, nil
}

// ----- helpers -----

func randomSerial() (*big.Int, error) {
	limit := new(big.Int).Lsh(big.NewInt(1), 128) // 128-bit serials
	return rand.Int(rand.Reader, limit)
}

// parseCertPEM parses the first CERTIFICATE block in `pemBytes`.
func parseCertPEM(pemBytes []byte) (*x509.Certificate, error) {
	for {
		block, rest := pem.Decode(pemBytes)
		if block == nil {
			return nil, errors.New("no PEM certificate found")
		}
		if block.Type == "CERTIFICATE" {
			return x509.ParseCertificate(block.Bytes)
		}
		pemBytes = rest
	}
}

// parsePrivateKeyPEM parses an Ed25519 private key in PKCS#8 PEM form.
func parsePrivateKeyPEM(pemBytes []byte) (ed25519.PrivateKey, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, errors.New("no PEM block")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, err
	}
	priv, ok := key.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("key is not Ed25519, got %T", key)
	}
	return priv, nil
}

// WriteCertAndKey writes a leaf cert + private key pair to two files.
// Convenience for CLI commands.
func WriteCertAndKey(certPath string, certPEM []byte, keyPath string, keyPEM []byte) error {
	if err := os.MkdirAll(filepath.Dir(certPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(certPath, certPEM, 0o644); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(keyPath), 0o700); err != nil {
		return err
	}
	return os.WriteFile(keyPath, keyPEM, 0o600)
}

// CNFromCert returns the Common Name of an X.509 certificate. Used by
// the operator to bind a TLS connection to a stele producer ID.
func CNFromCert(c *x509.Certificate) string { return strings.TrimSpace(c.Subject.CommonName) }
