"""Ed25519 keypair handling for stele producers.

Wraps the ``cryptography`` library so the rest of the SDK doesn't
touch low-level crypto APIs. The on-disk format is base64-encoded
Ed25519 private key bytes (matching what ``stele producer-init`` on
the Go side writes), so a key generated with this SDK is
interchangeable with one generated by the Go CLI.
"""

from __future__ import annotations

import base64
import os
from pathlib import Path
from typing import Union

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization


class PrivateKey:
    """An Ed25519 private key for a stele producer.

    The on-wire / on-disk encoding is the raw 32-byte seed (matching
    what Go's ``ed25519.PrivateKey.Seed()`` returns), base64-encoded
    when stored as text. This matches what ``stele producer-init``
    writes so keys are interchangeable.
    """

    __slots__ = ("_priv",)

    def __init__(self, priv: Ed25519PrivateKey) -> None:
        self._priv = priv

    # ---- factories ----

    @classmethod
    def generate(cls) -> "PrivateKey":
        return cls(Ed25519PrivateKey.generate())

    @classmethod
    def from_bytes(cls, b: bytes) -> "PrivateKey":
        """Load from either the raw 32-byte seed or Go's 64-byte expanded form.

        Go's ed25519 stores keys as 64 bytes: 32 seed || 32 pubkey.
        We accept both forms and use only the seed.
        """
        if len(b) == 64:
            b = b[:32]
        if len(b) != 32:
            raise ValueError(f"PrivateKey: expected 32 or 64 bytes, got {len(b)}")
        return cls(Ed25519PrivateKey.from_private_bytes(b))

    @classmethod
    def from_file(cls, path: Union[str, Path]) -> "PrivateKey":
        """Load a producer key from disk.

        Matches the format ``stele producer-init --out <path>`` writes:
        the base64-encoded 64-byte Ed25519 private (seed || pub), one
        line, optional trailing newline.
        """
        raw = Path(path).read_text().strip()
        return cls.from_bytes(base64.standard_b64decode(raw))

    @classmethod
    def from_b64(cls, s: str) -> "PrivateKey":
        return cls.from_bytes(base64.standard_b64decode(s.strip()))

    # ---- output ----

    def public_bytes(self) -> bytes:
        """Return the 32-byte Ed25519 public key."""
        return self._priv.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )

    def public_b64(self) -> str:
        return base64.standard_b64encode(self.public_bytes()).decode("ascii")

    def seed_bytes(self) -> bytes:
        """Return the raw 32-byte private seed."""
        return self._priv.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption(),
        )

    def to_bytes(self) -> bytes:
        """Return the Go-compatible 64-byte form (seed || pubkey)."""
        return self.seed_bytes() + self.public_bytes()

    def to_b64(self) -> str:
        """Return the base64 of the Go-compatible 64-byte form."""
        return base64.standard_b64encode(self.to_bytes()).decode("ascii")

    def to_file(self, path: Union[str, Path]) -> None:
        """Write the key to disk with 0600 permissions (matching the Go CLI)."""
        path = Path(path)
        path.write_text(self.to_b64() + "\n")
        try:
            os.chmod(path, 0o600)
        except OSError:
            # Best-effort on Windows; the file is at the user's umask.
            pass

    # ---- signing ----

    def sign(self, msg: bytes) -> bytes:
        return self._priv.sign(msg)


def generate_key() -> PrivateKey:
    """Convenience: PrivateKey.generate()."""
    return PrivateKey.generate()


def verify(pubkey: bytes, message: bytes, signature: bytes) -> bool:
    """Standalone Ed25519 verify — used by tests + the cross-check path."""
    try:
        pk = Ed25519PublicKey.from_public_bytes(pubkey)
        pk.verify(signature, message)
        return True
    except Exception:
        return False
