"""Cross-language interop: Python signs, Go's stele binary verifies.

These tests confirm the Python SDK produces envelope bytes that the
Go operator will accept. They use a fresh, isolated `steled` process
in `--init` mode so they can run from a clean state.

Skipped if the `steled` or `stele` binaries aren't built and on PATH.
Run `make build` from the repo root first, then ensure ``./bin`` is
on PATH or pass STELE_BIN_DIR.
"""

import json
import os
import shutil
import socket
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Iterator

import pytest

from stele import Producer, generate_key


REPO_ROOT = Path(__file__).resolve().parents[3]
BIN_DIR = Path(os.environ.get("STELE_BIN_DIR", REPO_ROOT / "bin"))


def _has_binary(name: str) -> bool:
    return (BIN_DIR / name).exists() or shutil.which(name) is not None


def _binary(name: str) -> str:
    p = BIN_DIR / name
    if p.exists():
        return str(p)
    return name  # fall back to PATH


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _wait_ready(url: str, timeout: float = 5.0) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=0.5) as resp:
                if resp.status == 200:
                    return
        except (urllib.error.URLError, ConnectionError):
            pass
        time.sleep(0.1)
    raise RuntimeError(f"server at {url} never became ready within {timeout}s")


@pytest.fixture(scope="module")
def steled_server() -> Iterator[str]:
    """Spin up a fresh ``steled`` process bound to localhost.

    Yields the base URL. Cleans up at end of module.
    """
    if not _has_binary("steled") or not _has_binary("stele"):
        pytest.skip(
            "steled/stele not found; build with `make build` from the repo root"
        )

    port = _free_port()
    base_url = f"http://127.0.0.1:{port}"
    with tempfile.TemporaryDirectory(prefix="stele-py-interop-") as dir_:
        env = {
            **os.environ,
            "STELE_LOG_LEVEL": "warn",
            "STELE_LOG_FORMAT": "json",
        }
        proc = subprocess.Popen(
            [
                _binary("steled"),
                "--addr", f":{port}",
                "--dir", dir_,
                "--origin", "interop.local/log",
                "--init",
                "--checkpoint-every", "0",
                "--anchor-every", "0",
                "--beacon", "",
                "--rotate-every", "0",
                "--watch-keys=false",
                "--watch-rate=false",
                "--read-log=false",
                "--tripwire-every", "0",
            ],
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        try:
            _wait_ready(base_url + "/readyz", timeout=10.0)
            yield base_url
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()


def test_python_envelope_accepted_by_go_server(steled_server):
    """A producer keypair generated by the Python SDK can enroll +
    submit an entry against a real `steled`. Any divergence in the
    canonical encoding would make this fail at /append."""
    priv = generate_key()
    prod = Producer(
        id="py-interop-prod",
        private_key=priv,
        server=steled_server,
    )
    # Enrol via proof-of-possession.
    confirm = prod.enroll(scope="logs:interop-test", validity_seconds=3600)
    assert "enrollment" in confirm or "producer" in confirm, confirm

    # Log a few entries.
    indices = []
    for i in range(5):
        resp = prod.log(source="py-interop", data=f"entry {i}".encode())
        idx = resp["entry"]["index"]
        indices.append(idx)
    assert indices == list(range(5)), indices

    # Operator-side independent verification: fetch the entry back
    # and confirm its leaf hash, then run the Go-side verifier on
    # the inclusion proof.
    cli = prod.client  # the SteleClient
    entry = cli.get(f"/api/v0/entries/{indices[-1]}")["entry"]
    assert entry["envelope"]["producer_id"] == "py-interop-prod"

    # The Go server returned a 200 for every append, which means
    # ed25519.Verify(canonical) succeeded with the public key the
    # Python SDK supplied. That is the entire interop claim:
    # Python's canonical bytes match the Go canonical bytes byte for byte.


def test_python_signed_envelope_replay_protected(steled_server):
    """The operator's replay-protection table uses SHA-256(canonical).
    If Python's SHA-256 disagreed with Go's, replay protection wouldn't
    work — submitting the same envelope twice would succeed twice.
    Confirm the envelope hash is consistent."""
    priv = generate_key()
    prod = Producer(
        id="py-replay-prod",
        private_key=priv,
        server=steled_server,
    )
    prod.enroll(scope="logs:replay-test")

    # Build one envelope, submit twice. Second submission must fail
    # with the operator's "replay" rejection (or any 4xx).
    from stele.envelope import new_envelope

    env = new_envelope(
        producer_id="py-replay-prod",
        public_key=priv.public_bytes(),
        source="replay-test",
        data=b"only once",
        time_nanos=1700000000000000000,  # fixed time so the hash is stable
    )
    env.sign(priv)

    body = {"envelope": env.to_dict(), "honeypot": False}
    # First submit succeeds.
    first = prod.client.post("/api/v0/append", body)
    assert "entry" in first

    # Second submit of the IDENTICAL envelope must fail.
    from stele.client import HTTPError
    with pytest.raises(HTTPError):
        prod.client.post("/api/v0/append", body)
